# ===============================
# MICROSERVICE CONFIGURATION
# ===============================
# Every microservice needs a unique name and port
spring.application.name=employee-service
server.port=8081

# ===============================
# NEON CLOUD DATABASE CONNECTION
# ===============================
# Notice the "jdbc:" added to the front of your Neon string
spring.datasource.url=jdbc:postgresql://ep-gentle-sun-anr0hz63-pooler.c-6.us-east-1.aws.neon.tech/employee_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JYKXu9e8tDQn
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# HIBERNATE & JPA SETTINGS
# ===============================
# 'update' tells Spring to automatically create the employees table
spring.jpa.hibernate.ddl-auto=update
# This prints the SQL queries to your terminal so you can see the magic happening
spring.jpa.show-sql=true