# ===============================
# MICROSERVICE CONFIGURATION
# ===============================
# Unique name and port for the Training Service
spring.application.name=training-service
server.port=8083

# ===============================
# NEON CLOUD DATABASE CONNECTION
# ===============================
# Pointed specifically to the new training_db
spring.datasource.url=jdbc:postgresql://ep-gentle-sun-anr0hz63-pooler.c-6.us-east-1.aws.neon.tech/training_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JYKXu9e8tDQn
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# HIBERNATE & JPA SETTINGS
# ===============================
# 'update' tells Spring to automatically create the skills and training tables
spring.jpa.hibernate.ddl-auto=update
# Prints the SQL queries to your terminal to verify database operations
spring.jpa.show-sql=true
# URL for the Identity Service (Port 8081)
identity.service.base-url=http://localhost:8081